### ISSUE TITLE
Cannot find module 'hono-openapi/zod' or its corresponding type declarations.

### ISSUE THREAD

**Issue by sonduong** [rhinobase/hono-openapi#11]
```
    "hono": "^4.6.11",
    "hono-openapi": "^0.1.5",
    "zod": "^3.23.8"
```

Env
- Node v20

tsconfig.json
```
{
  "compilerOptions": {
    "target": "ES6",
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "./dist",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "strict": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "noImplicitAny": true,
    "noEmitOnError": true
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": ["node_modules"]
}
```

I can not `import { resolver, validator } from 'hono-openapi/zod';`. Please advise,

**Comment by marcomuser** [comment]
The problem is twofold:
1. You configured tsconfig in a way so that it won't pick up the exports from hono-openapi's package.json. You probably want to set module: nodenext instead and set the type of your package to commonjs in your package.json. That way ts and node.js will both respect the exports in all your dependencies.
2. There is an issue in hono-openapi's exports in its package.json. The exports currently only point to the correct types for commonjs. This is the same issue as in issue #2. Having said that, in your case it should actually work if you follow the advice from the first point.
